name: Release GIMP Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        wget https://raw.githubusercontent.com/ivan-hc/GIMP-appimage/main/gimp
        chmod a+x ./gimp
        sudo ./gimp
        mkdir dist
        chmod a+x /opt/gimp/gimp
        VERSION=$(/opt/gimp/gimp --version | grep -Eo "[0-9]+([.][0-9]+)?+[+-]?")
        mv /opt/gimp/gimp dist/GNU_Image_Manipulation_Program-$VERSION-x86_64.AppImage

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: GNU_Image_Manipulation_Program-x86_64.AppImage
        path: 'dist'

  release:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: GNU_Image_Manipulation_Program-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              GNU_Image_Manipulation_Program-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
