name: GIMP Developer Edition Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 6 1/3 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update
        sudo apt install libfuse2
        wget https://raw.githubusercontent.com/ivan-hc/GIMP-appimage/main/gimp-dev-junest.sh
        chmod a+x ./gimp-dev-junest.sh
        ./gimp-dev-junest.sh
        mkdir dist
        mv *AppImage dist/
    - uses: gautamkrishnar/keepalive-workflow@v1
      with:
        gh_token: ${{ secrets.GH_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: GNU_Image_Manipulation_Program-DEV-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: GNU_Image_Manipulation_Program-DEV-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous Developer builds (JuNest Arch Linux-based AppImages)
            automatic_release_tag: continuous-dev
            prerelease: true
            draft: false
            files: |
              GNU_Image_Manipulation_Program-DEV-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
